const CONSTANTS = {
  DOLOGIN: "DOLOGIN",
  LOGOUT: "LOGOUT",
  COGNITO_USER_TO_STATE:"COGNITO_USER_TO_STATE",
  PUTUSERTOSTATE: "PUTUSERTOSTATE",
  PUSHNOTESTOSTATE: "PUSHNOTESTOSTATE"
}
export default CONSTANTS